
export default {
    CURRENT_VEHICLE_ID: 0,
    STORAGE_VEHICLE_LIST: "STORAGE_VEHICLE_LIST",
    STORAGE_FILL_GAS_LIST: "STORAGE_FILL_GAS_LIST",
    STORAGE_FILL_OIL_LIST: "STORAGE_FILL_OIL_LIST",
    STORAGE_AUTHORIZE_CAR_LIST: "STORAGE_AUTHORIZE_CAR_LIST",

    SETTING_KM_NEXT_OILFILL: 1000,
    SETTING_DAY_NEXT_AUTHORIZE_CAR: 730, // 2year
};
