export default {
    china_province:[ 
        { 
            "date":"2020-02-03T15:00:00.007Z",
            "provinces":[ 
                { 
                    "name":"Hubei",
                    "case":11177
                },
                { 
                    "name":"Zhejiang",
                    "case":724
                },
                { 
                    "name":"Guangdong",
                    "case":683
                },
                { 
                    "name":"Henan",
                    "case":566
                },
                { 
                    "name":"Hunan",
                    "case":521
                },
                { 
                    "name":"Anhui",
                    "case":408
                },
                { 
                    "name":"Jiangxi",
                    "case":391
                },
                { 
                    "name":"Chongqing",
                    "case":300
                },
                { 
                    "name":"Sichuan",
                    "case":271
                },
                { 
                    "name":"Jiangsu",
                    "case":254
                },
                { 
                    "name":"Shandong",
                    "case":246
                },
                { 
                    "name":"Beijing",
                    "case":212
                },
                { 
                    "name":"Shanghai",
                    "case":193
                },
                { 
                    "name":"Fujian",
                    "case":179
                },
                { 
                    "name":"Shaanxi",
                    "case":128
                },
                { 
                    "name":"Guangxi",
                    "case":127
                },
                { 
                    "name":"Hebei",
                    "case":118
                },
                { 
                    "name":"Yunnan",
                    "case":113
                },
                { 
                    "name":"Heilongjiang",
                    "case":109
                },
                { 
                    "name":"Liaoning",
                    "case":70
                },
                { 
                    "name":"Hainan",
                    "case":70
                },
                { 
                    "name":"Shanxi",
                    "case":66
                },
                { 
                    "name":"Gansu",
                    "case":51
                },
                { 
                    "name":"Tianjin",
                    "case":49
                },
                { 
                    "name":"Guizhou",
                    "case":46
                },
                { 
                    "name":"Ningxia",
                    "case":33
                },
                { 
                    "name":"Inner Mongolia",
                    "case":31
                },
                { 
                    "name":"Xinjia",
                    "case":31
                },
                { 
                    "name":"Jilin",
                    "case":24
                },
                { 
                    "name":"Qinghai",
                    "case":10
                },
                { 
                    "name":"Xizang",
                    "case":1
                }
            ]
        },
        { 
            "date":"2020-02-02T15:00:00.007Z",
            "provinces":[ 
                { 
                    "name":"Hubei",
                    "case":9074
                },
                { 
                    "name":"Zhejiang",
                    "case":661
                },
                { 
                    "name":"Guangdong",
                    "case":604
                },
                { 
                    "name":"Henan",
                    "case":493
                },
                { 
                    "name":"Hunan",
                    "case":463
                },
                { 
                    "name":"Anhui",
                    "case":340
                },
                { 
                    "name":"Jiangxi",
                    "case":333
                },
                { 
                    "name":"Chongqing",
                    "case":262
                },
                { 
                    "name":"Sichuan",
                    "case":236
                },
                { 
                    "name":"Jiangsu",
                    "case":231
                },
                { 
                    "name":"Shandong",
                    "case":225
                },
                { 
                    "name":"Beijing",
                    "case":183
                },
                { 
                    "name":"Shanghai",
                    "case":177
                },
                { 
                    "name":"Fujian",
                    "case":159
                },
                { 
                    "name":"Shaanxi",
                    "case":116
                },
                { 
                    "name":"Guangxi",
                    "case":111
                },
                { 
                    "name":"Hebei",
                    "case":104
                },
                { 
                    "name":"Yunnan",
                    "case":99
                },
                { 
                    "name":"Heilongjiang",
                    "case":95
                },
                { 
                    "name":"Liaoning",
                    "case":64
                },
                { 
                    "name":"Hainan",
                    "case":63
                },
                { 
                    "name":"Shanxi",
                    "case":56
                },
                { 
                    "name":"Gansu",
                    "case":45
                },
                { 
                    "name":"Tianjin",
                    "case":40
                },
                { 
                    "name":"Guizhou",
                    "case":38
                },
                { 
                    "name":"Ningxia",
                    "case":28
                },
                { 
                    "name":"Inner Mongolia",
                    "case":26
                },
                { 
                    "name":"Xinjia",
                    "case":23
                },
                { 
                    "name":"Jilin",
                    "case":21
                },
                { 
                    "name":"Qinghai",
                    "case":9
                },
                { 
                    "name":"Xizang",
                    "case":1
                }
            ]
        },
        { 
            "date":"2020-02-01T15:00:00.007Z",
            "provinces":[ 
                { 
                    "name":"Hubei",
                    "case":7153
                },
                { 
                    "name":"Zhejiang",
                    "case":599
                },
                { 
                    "name":"Guangdong",
                    "case":520
                },
                { 
                    "name":"Henan",
                    "case":422
                },
                { 
                    "name":"Hunan",
                    "case":389
                },
                { 
                    "name":"Anhui",
                    "case":297
                },
                { 
                    "name":"Jiangxi",
                    "case":286
                },
                { 
                    "name":"Chongqing",
                    "case":238
                },
                { 
                    "name":"Sichuan",
                    "case":207
                },
                { 
                    "name":"Shandong",
                    "case":202
                },
                { 
                    "name":"Jiangsu",
                    "case":202
                },
                { 
                    "name":"Shanghai",
                    "case":169
                },
                { 
                    "name":"Beijing",
                    "case":156
                },
                { 
                    "name":"Fujian",
                    "case":144
                },
                { 
                    "name":"Shaanxi",
                    "case":101
                },
                { 
                    "name":"Guangxi",
                    "case":100
                },
                { 
                    "name":"Hebei",
                    "case":96
                },
                { 
                    "name":"Yunnan",
                    "case":91
                },
                { 
                    "name":"Heilongjiang",
                    "case":80
                },
                { 
                    "name":"Liaoning",
                    "case":60
                },
                { 
                    "name":"Hainan",
                    "case":60
                },
                { 
                    "name":"Shanxi",
                    "case":47
                },
                { 
                    "name":"Tianjin",
                    "case":37
                },
                { 
                    "name":"Gansu",
                    "case":35
                },
                { 
                    "name":"Guizhou",
                    "case":29
                },
                { 
                    "name":"Ningxia",
                    "case":26
                },
                { 
                    "name":"Inner Mongolia",
                    "case":23
                },
                { 
                    "name":"Xinjia",
                    "case":18
                },
                { 
                    "name":"Jilin",
                    "case":17
                },
                { 
                    "name":"Qinghai",
                    "case":9
                },
                { 
                    "name":"Xizang",
                    "case":1
                }
            ]
        }
    ]
};